# Generated by Django 4.2.16 on 2026-05-02 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('audio_path', models.CharField(blank=True, max_length=1000)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('assembling', 'Assembling'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('indexing', 'Indexing'), ('completed', 'Completed'), ('error', 'Error')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_chunks', models.IntegerField(default=0)),
                ('received_chunks', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('assembling', 'Assembling'), ('complete', 'Complete'), ('error', 'Error')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('segments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisions', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mom', to='meetings.meeting')),
            ],
        ),
    ]
